<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtLink_titleProduct1</name>
   <tag></tag>
   <elementGuidId>4e6eb9e3-cab0-4bac-a7a2-ebcaa14ff133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div/div/div/div[1]/div[2]/div[1]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div/div/div/div[1]/div[2]/div[1]/a/div</value>
   </webElementProperties>
</WebElementEntity>
