<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtView_priceProduct1</name>
   <tag></tag>
   <elementGuidId>e75d751e-f07a-471a-9ffb-300628a7b6ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inventory_container&quot;]/div/div[1]/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inventory_container&quot;]/div/div[1]/div[2]/div[2]/div</value>
   </webElementProperties>
</WebElementEntity>
