<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtView_priceProduct2</name>
   <tag></tag>
   <elementGuidId>301c1b02-11dc-473f-926c-f0b7bac69987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inventory_container&quot;]/div/div[2]/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inventory_container&quot;]/div/div[2]/div[2]/div[2]/div</value>
   </webElementProperties>
</WebElementEntity>
