<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtView_descProduct1</name>
   <tag></tag>
   <elementGuidId>1bc84d4f-c4af-4b31-b0a2-64bce63e631e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inventory_container&quot;]/div/div[1]/div[2]/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inventory_container&quot;]/div/div[1]/div[2]/div[1]/div</value>
   </webElementProperties>
</WebElementEntity>
